application:
  subdomain: siyuan
  background_task: true
  public_path:
    - /

  upstreams:
    - location: /
      backend: http://siyuan-note-server:6806/

services:
  siyuan-note-server:
    image: docker.1ms.run/czyt/siyuan:v3.6.4
    environment:
      - LANG=zh_CN.UTF-8
      - TZ={{.U.siyuan_server_time_zone}}
      - PUID=1001
      - PGID=1002
      - SIYUAN_ACCESS_AUTH_CODE={{.U.siyuan_access_auth_code}}

    binds:
      - /lzcapp/var/data:/siyuan/workspace
