min_os_version: 1.5.0
name: 思源笔记
package: community.lazycat.app.siyuan-note
version: 3.6.3
description: "基于 GPL 协议，针对 siyuan-note 的修改版。去除了需要思源账号才能使用S3同步的限制的版本。"
homepage: https://github.com/dockers-x/siyuan
author: czyt

locales:
  zh:
    name: 思源笔记
    description: "基于 GPL 协议，针对 siyuan-note 的修改版。去除了需要思源账号才能使用S3同步的限制的版本。"
  en:
    name: Siyuan Note
    description: "A modified version of siyuan-note based on the GPL license. This version removes the restriction of requiring a Siyuan account to use S3 synchronization."
